/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;


/**
 *
 * @author crisc
 */
public class batalla extends javax.swing.JFrame {

    /**
     * Creates new form batalla
     */
    public batalla() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pokemon2 = new javax.swing.JLabel();
        pokemon1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Ataque1 = new javax.swing.JButton();
        Ataque2 = new javax.swing.JButton();
        Ataque3 = new javax.swing.JButton();
        Ataque4 = new javax.swing.JButton();
        fondoBatalla = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Entrenador1 = new javax.swing.JLabel();
        nombreEntrenador = new javax.swing.JLabel();
        nombrePokemon = new javax.swing.JLabel();
        vida = new javax.swing.JLabel();
        barraVida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(644, 487));
        setResizable(false);
        getContentPane().setLayout(null);

        pokemon2.setText("jLabel2");
        getContentPane().add(pokemon2);
        pokemon2.setBounds(429, 132, 38, 16);

        pokemon1.setText("jLabel1");
        getContentPane().add(pokemon1);
        pokemon1.setBounds(190, 260, 38, 16);

        jPanel1.setBackground(new java.awt.Color(62, 175, 173));
        jPanel1.setLayout(null);

        Ataque1.setBackground(new java.awt.Color(255, 255, 255));
        Ataque1.setText("jButton1");
        Ataque1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ataque1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ataque1MouseExited(evt);
            }
        });
        jPanel1.add(Ataque1);
        Ataque1.setBounds(20, 10, 130, 23);

        Ataque2.setBackground(new java.awt.Color(255, 255, 255));
        Ataque2.setText("jButton2");
        Ataque2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ataque2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ataque2MouseExited(evt);
            }
        });
        Ataque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ataque2ActionPerformed(evt);
            }
        });
        jPanel1.add(Ataque2);
        Ataque2.setBounds(180, 10, 130, 23);

        Ataque3.setBackground(new java.awt.Color(255, 255, 255));
        Ataque3.setText("jButton3");
        Ataque3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ataque3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ataque3MouseExited(evt);
            }
        });
        jPanel1.add(Ataque3);
        Ataque3.setBounds(20, 60, 130, 23);

        Ataque4.setBackground(new java.awt.Color(255, 255, 255));
        Ataque4.setText("jButton4");
        Ataque4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ataque4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ataque4MouseExited(evt);
            }
        });
        jPanel1.add(Ataque4);
        Ataque4.setBounds(180, 60, 130, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(320, 360, 330, 110);

        fondoBatalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("fondoBatalla.jpg"))); // NOI18N
        getContentPane().add(fondoBatalla);
        fondoBatalla.setBounds(0, 0, 649, 362);

        jPanel2.setBackground(new java.awt.Color(62, 175, 173));
        jPanel2.setLayout(null);

        Entrenador1.setText("jLabel3");
        jPanel2.add(Entrenador1);
        Entrenador1.setBounds(10, 10, 37, 16);

        nombreEntrenador.setText("jLabel4");
        jPanel2.add(nombreEntrenador);
        nombreEntrenador.setBounds(190, 10, 37, 16);

        nombrePokemon.setText("jLabel5");
        jPanel2.add(nombrePokemon);
        nombrePokemon.setBounds(10, 40, 37, 16);

        vida.setText("jLabel6");
        jPanel2.add(vida);
        vida.setBounds(190, 40, 37, 16);

        barraVida.setText("jLabel7");
        jPanel2.add(barraVida);
        barraVida.setBounds(10, 70, 37, 16);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 360, 320, 110);

        pack();
    }// </editor-fold>

    private void Ataque1MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Ataque1.setBackground(new Color (72, 192, 190));

    }

    private void Ataque1MouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Ataque1.setBackground(Color.white);
    }

    private void Ataque2MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Ataque2.setBackground(new Color (72, 192, 190));
    }

    private void Ataque2MouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Ataque2.setBackground(Color.WHITE);
    }

    private void Ataque3MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Ataque3.setBackground(new Color (72, 192, 190));
    }

    private void Ataque3MouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Ataque3.setBackground(Color.white);
    }

    private void Ataque4MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Ataque4.setBackground(new Color (72, 192, 190));
    }

    private void Ataque4MouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Ataque4.setBackground(Color.white);
    }

    private void Ataque2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new batalla().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JButton Ataque1;
    private javax.swing.JButton Ataque2;
    private javax.swing.JButton Ataque3;
    private javax.swing.JButton Ataque4;
    private javax.swing.JLabel Entrenador1;
    private javax.swing.JLabel barraVida;
    private javax.swing.JLabel fondoBatalla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombreEntrenador;
    private javax.swing.JLabel nombrePokemon;
    private javax.swing.JLabel pokemon1;
    private javax.swing.JLabel pokemon2;
    private javax.swing.JLabel vida;
    // End of variables declaration
}
